export const demoLines = [
  { kind: "command", text: "$ legacy-change-radar demo" },
  { kind: "space", text: "" },
  { kind: "heading", text: "# Legacy Change Radar" },
  { kind: "muted", text: "Source: bundled harbor-app sample" },
  { kind: "space", text: "" },
  { kind: "strong", text: "3 files · +6 additions · −3 deletions" },
  { kind: "space", text: "" },
  { kind: "heading", text: "Review signals" },
  { kind: "danger", text: "HIGH  migration · migrations/20260828_add_berth_depth.sql" },
  { kind: "plain", text: "      ALTER TABLE berths ADD COLUMN depth_cm INTEGER;" },
  { kind: "warn", text: "MED   public API · src/routes/berths.ts" },
  { kind: "warn", text: "MED   configuration · config/harbor.toml" },
  { kind: "space", text: "" },
  { kind: "heading", text: "Dependency edges" },
  { kind: "plain", text: "IN    src/jobs/tide-reminder.ts → src/routes/berths.ts" },
  { kind: "plain", text: "OUT   src/routes/berths.ts → src/stores/berths.ts" },
  { kind: "space", text: "" },
  { kind: "heading", text: "Required named checks" },
  { kind: "plain", text: "[ ] migration-review" },
  { kind: "plain", text: "[ ] public-api-contract" },
  { kind: "plain", text: "[ ] dependent-tests" },
  { kind: "space", text: "" },
  { kind: "muted", text: "Review context only. This does not prove correctness." },
];
